language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - libv8-dev
    - os: linux
      addons:
        apt:
          packages:
            - libnode-dev
    - os: osx
