language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      env: R_CODECOV=true
      sudo: required
    - os: osx
      osx_image: xcode8.1
      latex: false
    - os: osx
      osx_image: xcode6.1
      latex: false

addons:
  apt:
    packages:
      - libv8-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: true
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi
